# Jacobian Inverse Kinematic Solver Examples

This file demonstrates the various functions that are available in the jacobian_ik library by Michael Lauria.




In [1]:
from spatialmath import SO3
from webots import *
from jacobian_ik import *

# 1. Move along a local coordinate axis

Options are x, y or z. 

In [ ]:
start_pos = [0, -1.382, -1.13, -2, 1.63, 3.142]

goToPose(start_pos)

_, start_pose_transform = getCurrentPose()
print(f"current space frame transform: {start_pose_transform.round(3)}")

print("moving down 40 cm ...")
output, desiredPose = moveTo('z', -0.4) # move along local x,y or z
print(f"target pose: {desiredPose.round(3)}")

error = getSpaceFrameError(desiredPose)
print(f"error: {error}")
print(f"linear error: {np.linalg.norm(error[:3])}")
print(f"angular error: {np.linalg.norm(error[3:])}")

_, pose = getCurrentPose()
print(f"actual: {pose.round(3)}")
print(error)


# 2. Move to pose

In [6]:
joint_angles, pose = getCurrentPose()
print(f"actual pose: {pose.round(3)}")

print("moving back to start pose (using transform directly) ...")
print("see _moveTo()")
output = moveToPose(start_pose_transform, joint_angles)
print(f"target pose: {start_pose_transform.round(3)}")

error = getSpaceFrameError(start_pose_transform)
print(f"space frame error: {error}")
print(f"space frame linear error: {np.linalg.norm(error[:3])}")
print(f"space frame angular error: {np.linalg.norm(error[3:])}")

_, pose = getCurrentPose()
print(f"actual: {pose.round(3)}")
print(error)

actual pose: [[ 0.251  0.939 -0.237  0.355]
 [ 0.837 -0.087  0.54  -0.127]
 [ 0.487 -0.334 -0.807  0.733]
 [ 0.     0.     0.     1.   ]]
moving back to start pose (using transform directly) ...
see _moveTo()
target pose: [[-0.026  0.98   0.199  0.355]
 [ 0.998  0.015  0.059 -0.127]
 [ 0.055  0.2   -0.978  0.733]
 [ 0.     0.     0.     1.   ]]
space frame error: [ 6.53406530e-05 -5.57693466e-05 -3.09818524e-05 -6.66536491e-05
 -1.08252702e-04  2.41397713e-07]
space frame linear error: 9.132084168940669e-05
space frame angular error: 0.0001271275529849477
actual: [[-0.026  0.98   0.199  0.355]
 [ 0.998  0.015  0.059 -0.127]
 [ 0.055  0.2   -0.978  0.733]
 [ 0.     0.     0.     1.   ]]
[ 6.53406530e-05 -5.57693466e-05 -3.09818524e-05 -6.66536491e-05
 -1.08252702e-04  2.41397713e-07]


# 3. Move to specific orientation

In [4]:
rotation = SO3.RPY([30, 30, 0], unit="deg")
joint_angles, pose = getCurrentPose()
target = SE3(SO3(rotation.A @ pose[:3, :3])).A

# keep the current location, just rotate
target[:3, 3] = pose[:3, 3]
print(target)

print("moving ...")
output = moveToPose(target, joint_angles)
print(f"target pose: {target.round(3)}")

error = getSpaceFrameError(target)
print(f"space frame error: {error}")
print(f"space frame linear error: {np.linalg.norm(error[:3])}")
print(f"space frame angular error: {np.linalg.norm(error[3:])}")

_, pose = getCurrentPose()
print(f"actual: {pose.round(3)}")
print(error)

[[ 0.25052672  0.93869946 -0.2368115   0.35475676]
 [ 0.83689985 -0.08702947  0.54039292 -0.12739381]
 [ 0.48665696 -0.33357038 -0.80740065  0.73313767]
 [ 0.          0.          0.          1.        ]]
moving ...
target pose: [[ 0.251  0.939 -0.237  0.355]
 [ 0.837 -0.087  0.54  -0.127]
 [ 0.487 -0.334 -0.807  0.733]
 [ 0.     0.     0.     1.   ]]
space frame error: [-2.90811195e-05  5.32923201e-05  3.09845210e-05  6.19790781e-05
  2.22498028e-05 -1.63155627e-05]
space frame linear error: 6.81602775510635e-05
space frame angular error: 6.784288781221992e-05
actual: [[ 0.251  0.939 -0.237  0.355]
 [ 0.837 -0.087  0.54  -0.127]
 [ 0.487 -0.334 -0.807  0.733]
 [ 0.     0.     0.     1.   ]]
[-2.90811195e-05  5.32923201e-05  3.09845210e-05  6.19790781e-05
  2.22498028e-05 -1.63155627e-05]
